### ISSUE TITLE
Error when trying to configure ComputeSwitch in Windows Admin Center

### ISSUE THREAD

**Issue by squasta** [Azure/AzureStackHCI-EvalGuide#14]
Following instructions on https://github.com/Azure/AzureStackHCI-EvalGuide/blob/main/nested/steps/4_AzSHCICluster.md I got an error message at ComputeSwitch creation in Windows Admin Center

![Pb install AZHCI 1](https://user-images.githubusercontent.com/13031988/88283586-f8192600-cceb-11ea-955b-16f15ea9b3d1.png)

This is a Nested setup and I followed all instructions (except I change 192.168.0.x/24 IP range with my own 192.168.10.x/24)

**Comment by mattmcspirit** [comment]
Hi - please see steps here: https://github.com/Azure/AzureStackHCI-EvalGuide/issues/8 to resolve. Just run the updated PS to install the PS modules on your nodes and it should allow you to proceed.

**Comment by squasta** [comment]
Thanks it solves the issue on one VM not the other that seems to have a DNS / WinRM problem. I will break everything and rebuild instead of losing time trying to solve that.

**Comment by mattmcspirit** [comment]
Thanks - if you're seeing a WinRM issue at cluster validation, the fix is easy, and quick - see here: https://github.com/Azure/AzureStackHCI-EvalGuide/blob/main/nested/steps/4_AzSHCICluster.md#troubleshooting-cluster-validation-issues

Thanks for testing!
