### ISSUE TITLE
Cluster Validation Failure

### ISSUE THREAD

**Issue by Guitarist7** [Azure/AzureStackHCI-EvalGuide#36]
Hello, I'm getting the "Test Report" issue when trying to validate the cluster.  I've followed the workaround, but still it persists.  Oddly I also have notifications in Windows Admin Center stating "successfully validated the cluster".  However the test report issue is preventing me from progressing to the next step.  Any help would be much appreciated!

**Comment by ElhamNsr** [comment]
Are you also not getting the CredSSP Popup?
i am also got stuck at "validate cluster"

**Comment by mattmcspirit** [comment]
@Guitarist7 - What are your locale settings?

AzSHCI Node locale - en-us?
WAC machine locale - en-us?
Edge browser on WAC machine locale - en-us?

I've only seen this issue when the locales don't all match - it's a bug that is being worked on I believe.

**Comment by Guitarist7** [comment]
Hello, it turned out to need set-culture and set-uiculture to be en-us on both nodes and mgmt01.  All sorted now - and back to connectivity issues registering the cluster to Azure.  Thanks for your time and responses, they're very much appreciated!

**Comment by mattmcspirit** [comment]
Thanks for the update - let us know if you get any other blockers!
