### ISSUE TITLE
Consolidate node name and IP address variable at the beginning

### ISSUE THREAD

**Issue by erjosito** [Azure/AzureStackHCI-EvalGuide#37]
When creating a second host, the user needs to modify the value of the $nodeName and $newIP variables. However, the $nodeName is set multiple times during the script, and the $newIP is pretty buried in the code and hard to spot. I would suggest to put those at the very beginning of the code in https://github.com/Azure/AzureStackHCI-EvalGuide/blob/main/nested/steps/3b_AzSHCINodesPS.md, so that the code is more reusable.

Thanks!

**Comment by mattmcspirit** [comment]
Thank you - great catch.  I'm working on some updates, so will capture this in an updated version.  Thank you!

**Comment by mattmcspirit** [comment]
Hey - this should be fixed in the updated steps - thanks!
