### ISSUE TITLE
Azure registration PoSH modules required

### ISSUE THREAD

**Issue by carlosmayol** [Azure/AzureStackHCI-EvalGuide#38]
Even when using a MGMT or from the HOST itsself, these are the modules required for the registration:
Install-Module Az.Accounts
Install-Module Az.Resources
Install-Module AzureAD
Install-Module Az.StackHCI (only this one is mentioned)

**Comment by mattmcspirit** [comment]
Hi - thanks for this.  The Install-Module Az.StackHCI is the key one, as that allows you to start the registration process, and as part of that, it will download the other required modules (automatically, or at least it should be).

Please let me know if that's not happening in your environment.

Thanks!

**Comment by carlosmayol** [comment]
Hey Matt, it does not happen on Server, didn't try on Win10. Using one of the HOST nodes to register.

**Comment by carlosmayol** [comment]
Just created a pull request with the changes, feel free to check and accept/discard :) I will add some more around the AAD process...

**Comment by mattmcspirit** [comment]
Thanks - i'll be working through some updates to the docs soon, so will retest and accept/discard at that point - thanks! :)

**Comment by mattmcspirit** [comment]
Hey - this should be fixed in the updated steps - for me, it automatically installed them.  I'll re-open if this happens again.
