### ISSUE TITLE
Part 3a of guide missing $nodeName

### ISSUE THREAD

**Issue by the-chad-at-ms** [Azure/AzureStackHCI-EvalGuide#40]
Part 3a of this guide under section "Enable the Hyper-V Role on your Azure Stack HCI Node" is missing the $nodeName in the script.
(https://github.com/Azure/AzureStackHCI-EvalGuide/blob/main/nested/steps/3a_AzSHCINodesGUI.md#enable-the-hyper-v-role-on-your-azure-stack-hci-node)
As a workaround, I created the variable for each node and ran through the script.

**Comment by mattmcspirit** [comment]
Thank you!  Will be fixed in the coming days as part of a larger rev - thank you!

**Comment by mattmcspirit** [comment]
Hey - this should be fixed in the updated steps - thanks!
