### ISSUE TITLE
Recommend adding "start-sleep" for each "Rebooting node for changes to take effect" sections

### ISSUE THREAD

**Issue by the-chad-at-ms** [Azure/AzureStackHCI-EvalGuide#41]
Not an issue...more of a suggestion.

Within the https://github.com/Azure/AzureStackHCI-EvalGuide/blob/main/nested/steps/3a_AzSHCINodesGUI.md#enable-the-hyper-v-role-on-your-azure-stack-hci-node section of 3a, I would suggest adding a sleep timer between commands for stop-vm and start-vm to stop powershell dropping an error.
This was picked up on my HV host as its slightly older but would reduce false positives.
I used 5 seconds for each and seemed a good amount of time.
If included a screenshot/snippet of what I put in each of the "Rebooting node for changes to take effect" sections:

![image](https://user-images.githubusercontent.com/40874599/98046146-c03e8480-1e7d-11eb-9e7c-84e11b660943.png)

**Comment by mattmcspirit** [comment]
Great feedback - thanks!  I'll add to the next rev of the content!

**Comment by mattmcspirit** [comment]
Hey - this should be fixed in the updated steps - thanks!

**Comment by the-chad-at-ms** [comment]
No problem for the feedback...thanks for including it.
