### ISSUE TITLE
Cannot create cluster in Azure VM - stuck at "define networks"

### ISSUE THREAD

**Issue by jonathan-vella** [Azure/AzureStackHCI-EvalGuide#50]
hey folks, seems like i have hit a brick wall.  i cannot get past the "define networks" section.  behavior is very erratic; sometime i get lucky and the following error is displayed:

"We couldn’t configure network adapters. Please try again. Error: Connecting to remote server 11.0.0.6 failed with the following error message : WinRM cannot complete the operation. Verify that the specified computer name is valid, that the computer is accessible over the network, and that a firewall exception for the WinRM service is enabled and allows access from this computer. By default, the WinRM..." --> to eliminate this i have created a gpo which will allow some traffic

In some other cases, WAC itself crashes. When this happens WAC displays thh following "Error Couldn't get user info. Source
Go to source. Type Error Message ajax error

And in some others, some NICs do get configured. What is common is that CPU usage across all HCI nodes goes up to 25%.
Any hints or ideas? thanks.

**Comment by mattmcspirit** [comment]
Hi - thanks for raising this - I've seen this issue recently too, and we're investigating. The hope is that we can fix soon.

**Comment by joekellyco** [comment]
I am seeing similar issues now where I am unable to provision the virtual switches: 
![image](https://user-images.githubusercontent.com/51091803/106396659-9df9cb80-63c6-11eb-91d6-81b38c079b70.png)

**Comment by liamfoneill** [comment]
![image](https://user-images.githubusercontent.com/1243172/106806564-07e0d200-6660-11eb-95f8-b4b203f5f4e2.png)

+1 on this issue for me too. Are there any workarounds currently?

**Comment by liamfoneill** [comment]
Got a bit further. The CredSSP message popped up and when I clicked ok I got this failure on the 4 storage NICs 
![image](https://user-images.githubusercontent.com/1243172/106807386-ff3ccb80-6660-11eb-91c2-e62f212ecc8e.png)

**Comment by liamfoneill** [comment]
actually I figured out (for me at least) restarting WINRM on both Stack HCI nodes got it working.

**Comment by liamfoneill** [comment]
@mattmcspirit did we ever get to the bottom of this?

**Comment by mohaom** [comment]
with last "Cluster Creation" extension update it worked smoothly for me :)

**Comment by liamfoneill** [comment]
can confirm that the new cluster creation extension fixed it for me too
