### ISSUE TITLE
Cannot Create VM

### ISSUE THREAD

**Issue by liamfoneill** [Azure/AzureStackHCI-EvalGuide#51]
I followed the guide pretty much to the letter but right at the end, I am unable to create any VMs (with a not-to-helpful error message).

![image](https://user-images.githubusercontent.com/1243172/107572602-653acd00-6be4-11eb-8987-58d83a0ab53f.png)

It seems to create the hard disk but a tiny one (4096KB). I specified 5GB as per the guide.

![image](https://user-images.githubusercontent.com/1243172/107572752-974c2f00-6be4-11eb-9656-1a95ee942ea8.png)

I'm running under nested Virtualization on my AMD Desktop Machine. I have collected diagnostics ( at  https://file.io/cyMZyGuTgJPu ). Happy to do a screenshare

**Comment by liamfoneill** [comment]
I was able to create a machine but without a disk

![image](https://user-images.githubusercontent.com/1243172/107574487-af24b280-6be6-11eb-9286-b390327ba2dd.png)

**Comment by mattmcspirit** [comment]
Was the first creation attempt prior to successful registration, or after?

**Comment by liamfoneill** [comment]
before. So is that expected that the VM creation will fail unless cluster is registered? (I have since been able to register the cluster in the East US region and I can now create VMs)
