### ISSUE TITLE
Cannot Register Cluster in West Europe

### ISSUE THREAD

**Issue by liamfoneill** [Azure/AzureStackHCI-EvalGuide#52]
It seems like a bug that when I go to register a cluster one of the three option is West Europe yet I cannot get it to register there as it  says it is not available. I had to register it in East US to get it to finally register. Is that going to either be removed from the drop down list or is West Europe support immanent?

**Comment by mattmcspirit** [comment]
Hi Liam - the registration issue would have caused the VM not to be created (as per your other issue) - unless the cluster is registered, you can't create VMs. That said, I believe West Europe should be supported, however I'll double check.

Was the registration done via WAC or PowerShell?

Thanks,
Matt

**Comment by liamfoneill** [comment]
WAC

**Comment by mattmcspirit** [comment]
Great - thanks - just waiting on confirmation of regions but glad East US worked for you.

**Comment by mattmcspirit** [comment]
Hey - West Europe is live, along with East US, Southeast Asia, however there may be a bug in WAC. If you tried with PS instead, that would likely work. We'll ensure this gets fixed for a future build.  Thanks for flagging!
