### ISSUE TITLE
Cluster Manager says there are update available when there are not

### ISSUE THREAD

**Issue by liamfoneill** [Azure/AzureStackHCI-EvalGuide#53]
![image](https://user-images.githubusercontent.com/1243172/107573954-17bf5f80-6be6-11eb-9211-4d81007e7e41.png)

![image](https://user-images.githubusercontent.com/1243172/107574016-23128b00-6be6-11eb-8a72-0b65927086c1.png)

**Comment by mattmcspirit** [comment]
Thanks Liam - will double check on this. Thanks for flagging - may just be a timing/refresh period issue.
