### ISSUE TITLE
Set-VMProcessor

### ISSUE THREAD

**Issue by j-Mikolajek** [Azure/AzureStackHCI-EvalGuide#56]
I am not sure if this is something I am doing wrong. I am working through the step **Deploy nested Azure Stack HCI 20H2 nodes with the GUI**.

The command I ran(with the VM powered off):

Set-VMProcessor -VMName AZSHCINODE01 -ExposeVirtualizationExtensions $true -Verbose

The command looked to run without error. I proceeded through the guide without issue until I came to the point where I tried to create the cluster in Windows Admin Center.  Everything went ok until **Install Features** step. Every feature except Hyper-V installed fine. The message regarding the installation of Hyper-V stated:

"Please ensure nested virtualization is enabled in order to successfully install Hyper-V on..."

In troubleshooting, I deployed a separate VM, this time running Windows 2019 Server. I went ahead and tried to install the Hyper-V role. At this point, I neglected to run that **Set-VMProcessor...** command against it. The role failed with a similar message as the Azure HCI vm.

I powered off the 2019 Server and ran that **Set-VMProcessor...** command. Again, it looked to run just fine.

I started up the 2019 server and retried installing the Hyper-V role. This time, the role installed successfully and I have this test box running fine.

This issue seems to be applying the **Set-VMProcessor** command against a vm running Azure Stack HCI OS.

Please let me know if this is helpful.

Thanks,

Jim

**Comment by mattmcspirit** [comment]
Hi Jim - thanks for this.  This is documented here:

- GUI path: https://github.com/Azure/AzureStackHCI-EvalGuide/blob/main/nested/steps/3a_AzSHCINodesGUI.md#enable-the-hyper-v-role-on-your-azure-stack-hci-20h2-node
- PS path: https://github.com/Azure/AzureStackHCI-EvalGuide/blob/main/nested/steps/3b_AzSHCINodesPS.md#enable-the-hyper-v-role-on-your-azure-stack-hci-20h2-node

You need to install the Hyper-V role using this step, rather than doing it with WAC.

Hope that helps.
Matt

**Comment by j-Mikolajek** [comment]
Thank you! That worked great!

Jim

**Comment by valireality** [comment]
> Hi Jim - thanks for this. This is documented here:
> 
> * GUI path: https://github.com/Azure/AzureStackHCI-EvalGuide/blob/main/nested/steps/3a_AzSHCINodesGUI.md#enable-the-hyper-v-role-on-your-azure-stack-hci-20h2-node
> * PS path: https://github.com/Azure/AzureStackHCI-EvalGuide/blob/main/nested/steps/3b_AzSHCINodesPS.md#enable-the-hyper-v-role-on-your-azure-stack-hci-20h2-node
> 
> You need to install the Hyper-V role using this step, rather than doing it with WAC.
> 
> Hope that helps. Matt

Links are dead :(
i have same problem.

**Comment by vovogit** [comment]
Hi, valireality

I found PS scripts in archives.
(https://github.com/Azure/AzureStackHCI-EvalGuide/blob/main/archive/steps/3a_AzSHCINodesGUI.md)

This scripts works well in 21H2 version.

thanks,
