### ISSUE TITLE
Issue: The NIC is getting changed to DHCP after Static IP 

### ISSUE THREAD

**Issue by kmyth1980** [Azure/AzureStackHCI-EvalGuide#58]
Hello Team,

I've setup the NICs with the static IP address. However, after reboot the IP address chnaged back to DHCP. This is happening for almost all NICs. When I'm trying to change the IP address back to static then I get below error.

"Failed to release DHCP lease"
Result Code: 83

PFA screenshot for your reference. PLease can you help?
![HCI_NICs Error code](https://user-images.githubusercontent.com/86222806/123545516-07afb300-d776-11eb-8e0e-bd5e3049aa12.jpg)

**Comment by mattmcspirit** [comment]
Hmm, i've only seen this once and I couldn't figure it out, so created a new HCI node and this worked fine.

- Is this on both of your nodes?
- If you shut the nested HCI node down, remove all vNICs in Hyper-V Manager, apply, then add 4 replacement vNICs, then try again, does that change anything?
- If that doesn't work, can you create a new node and see if the problem persists?

**Comment by kmyth1980** [comment]
Sure, Matt. Please let me try and see if this works. I will keep you posted. Thanks for your kind response. really appreciated.
I'm working for Microsoft (v-khanmoha@microsoft.com). I will reach you on chat if you are fine.

**Comment by mattmcspirit** [comment]
Sure, please do - also, if you're interested, you could redeploy using the whole environment (assuming you're running in an Azure VM) using this guide - https://github.com/mattmcspirit/hybridworkshop/blob/main/steps/1_DeployAzureVM.md, as it deploys all the DC, Mgmt and HCI nodes for you :)

**Comment by kmyth1980** [comment]
I have redeployed HCI nodes and all good. Thanks Matt for helping.

**Comment by mattmcspirit** [comment]
Great! Thanks!
