### ISSUE TITLE
Access denied when running "get-azurestackhci" on MGMT node

### ISSUE THREAD

**Issue by marcoarroyo41** [Azure/AzureStackHCI-EvalGuide#60]
Hi Matt,

Thoughts on why AZSHCINODE01 might be denying MGMT access?

![Capture](https://user-images.githubusercontent.com/62313730/124290587-38e30700-db19-11eb-9b83-4d0fa080c4f9.PNG)

**Comment by marcoarroyo41** [comment]
Also this error please!
![Capture](https://user-images.githubusercontent.com/62313730/124290785-7778c180-db19-11eb-9d86-0c25d3386653.PNG)

**Comment by mattmcspirit** [comment]
For the first one, please check you're logged into MGMT01 as domain\labadmin - you can also try passing your credentials directly in the Invoke-Command by using the -Credential:

Invoke-Command -ComputerName Server01 -Credential Domain01\User01 -ScriptBlock { }

For the second one, this is a bug that's currently being worked on. The registration should still complete successfully and you can check by running Get-AzureStackHCI on one of the nodes and it should show as registered.

If you don't want to see the error, you should be able to use:

-EnableAzureArcServer:$false

at the end of your registration command.
