### ISSUE TITLE
CredSSP

### ISSUE THREAD

**Issue by mysoultan** [Azure/AzureStackHCI-EvalGuide#61]
I was able to install the Cluster with two node. I was trying to install AKS on the Node. however, I am keep getting the CredSSP error.  I went disabling and enabled the CredSSP with role Server on the MGMT01, and disable and enable the CredSSP with Client role on the nodes. still the same. 

Error: Couldn't enable CredSSP delegation. Error: Processing data from remote server MGMT01 failed with the following error message: Could not find the role capability, 'MS-CredSSP-Admin'. The role capability must be a file named 'MS-CredSSP-Admin.psrc' within a 'RoleCapabilities' directory in a module in the current module path. For more information, see the about_Remote_Troubleshooting Help topic.

**Comment by mattmcspirit** [comment]
Hey - i saw your note internally, did you manage to fix this by copying the modules from another machine?
