### ISSUE TITLE
AzureStackHCI-EvalGuide - Unable to Configure Networking on Nested Setup

### ISSUE THREAD

**Issue by pradipsaujani** [Azure/AzureStackHCI-EvalGuide#62]
I am attempting to set up Azure Stack HCI cluster for evaluation by following the guide as part of the HCI 20H2 using Nested Virtualization
https://github.com/Azure/AzureStackHCI-EvalGuide/blob/main/nested/steps/4_AzSHCICluster.md

I have been able to proceed through parts 1-3 and have my management VM, my domain controller, and 2 nodes set up, but am getting stuck during part 4 (creating cluster) of the guide in the Networking Step 2.5 - Define Networks. 
When I get to Networking, I am able to set up everything until the Define networks step. There, I have left Ethernet 2 alone, and set up Ethernet 3 to be Storage 1 on each node, and Ethernet 4 to be Storage 2 on each node. Regardless of how I set up the IP addresses, I cannot get the cluster report to generate and proceed to the actual cluster creation.

![Error-define networks](https://user-images.githubusercontent.com/88159959/127675952-3ab07b78-71f2-456e-b792-b6dce79daed1.png)

Error Details:
![Configure adapter error details](https://user-images.githubusercontent.com/88159959/127676458-500509a1-6677-4d49-89cf-d2f97331646d.png)

I haven't been able to find anything about why the operations are failing, or what I can do to possibly resolve it. Can anyone help me out, either with some step-by-step guides.

I've checked the following post and the others related to the AzureStackHCI-EvalGuide
https://docs.microsoft.com/en-us/answers/questions/236938/unable-to-configure-networking-on-nested-setup.html

As per the guide I have run the related commands to Troubleshooting cluster validation issues CredSSP issue - "During testing, you may see an issue initiating cluster validation due to a CredSSP issue."

Help!
Thanks Pradip!

**Comment by mattmcspirit** [comment]
Hey - thanks for getting in touch.

Firstly, can you confirm you're logged into MGMT01 with domain\labadmin, and not just administrator?

Secondly, have you received a CredSSP popup at all?

![image](https://user-images.githubusercontent.com/20191274/127681277-06948b84-a110-43cf-b368-9a0d8410a731.png)

Thanks,
Matt

**Comment by pradipsaujani** [comment]
Hi Matt, thanks for replying
Yes correct, logged into MGMT01 with domain\labadmin and no CredSSP popup received.
Thanks!

**Comment by mattmcspirit** [comment]
OK great , so here's what i would try - first, in Edge, in Settings, turn off the popup blocking, then close all browser instances, open a fresh one and walk through the wizard again - when you get to the networks section, check for popups and if you don't see one, minimize WAC and make sure it hasn't popped up behind the active window - you should definitely see this popup and will need to click yes to continue through the wizard successfully.

**Comment by pradipsaujani** [comment]
Hey Matt, sorted!

![image](https://user-images.githubusercontent.com/88159959/127697415-1c2fc5b1-d9fb-47ca-b3bf-f9a81c328671.png)

![image](https://user-images.githubusercontent.com/88159959/127697502-5cb06131-39ee-4986-84c5-737496e4f649.png)

Done as suggested:
1. In Edge, in Settings, turn off the popup blocking
2. Closed browser
3. Logged out and restarted the server
4. Logged into the server as ladadmin, changed the browser to be logged into labadmin 
4. Re-ran all the steps and it worked

Massive thanks for your quick help!

**Comment by mattmcspirit** [comment]
Greaat, thanks!
