### ISSUE TITLE
failed to deployment AzureStack HCI Nested SDN in Azure VM 

### ISSUE THREAD

**Issue by ShawnBian** [Azure/AzureStackHCI-EvalGuide#63]
Hello ,I tried to deploy AzureStack HCI SDN, All the NC,MUX,GW,VM are good to deploy ,finnally it failed to deploy and get the error below :
C:\ISO\SDN-master\SDN-master\SDNExpress\scripts\SDNExpress.ps1 : Terminating error was thrown while executing
'C:\Windows\system32\WindowsPowerShell\v1.0\Modules\networkcontroller\Microsoft.NetworkController.Powershell.dll' operation on the
server side endpoint 'https://sdn.azshci.local/networking/V1/operations/063640bb-c765-4b4f-b2f1-4feaf208514b'.
At line:1 char:1
+ .\SDNExpress.ps1 -ConfigurationDataFile MultiNodeSampleConfig.psd1 -V ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (https://sdn.azs...f1-4feaf208514b:Uri) [SDNExpress.ps1], InvalidOperationException
    + FullyQualifiedErrorId : ODataEndpointProxyInvokeFailure,SDNExpress.ps1

 that would be really appreciated if someone knew this issue and help me out of this issue.

**Comment by ShawnBian** [comment]
please refer the attachment for error in details. thanks 


[52861c2d85d74dce866eefbc5acd1144 (1).txt](https://github.com/Azure/AzureStackHCI-EvalGuide/files/6998306/52861c2d85d74dce866eefbc5acd1144.1.txt)

**Comment by mgodfre3** [comment]
ShawnBian, SDN will require some routed components that can not be achieved in a Nest scenerio without the use of a Nested Router or "Top-of-Rack" router into the HCI deployment. You will run into similar issues to what you are seeing here in your deployment. If you would like to try out SDN with Azure Stack HCI, please try aka.ms/azstackhcisandbox, that deployment will deploy out SDN in a 2 node ASHCI cluster, with the required Virtual Router to successfully deploy SDN so you can test out the the features.  Sorry, but nested SDN on top of really SDN in Azure makes things a bit tricker, and you wouldn't run into these issues in a real, hardware based deployment. Good luck.
