### ISSUE TITLE
Major Issue in Lab 4 - Cannot get past Lab 4 beginning - Create Volume, no error, no information in the console

### ISSUE THREAD

**Issue by WVDAdminTF** [Azure/AzureStackHCI-EvalGuide#69]
The Update Lab Guide for Azure Stack HCI 21 H2 is faulty beyond - Part 3 - Explore Azure Stack HCI Management

The Azure Stack HCI 21H2 - Evaluation Guide - https://github.com/Azure/AzureStackHCI-EvalGuide works fine up till Lab 3 Perfectly.

**Lab 4 has major issues when creating Volume** - https://github.com/Azure/AzureStackHCI-EvalGuide/blob/main/deployment/steps/4_ExploreAzSHCI.md#create-volumes-for-vms

I have run in around 7 different instance in 4 different Azure Tenants and was not able to get past below this point.

There is no Error, no notification, nothing to check after clicking on create volume "**_In Size on HDD, specify 20GB for the size of the volume, then click Create._**"

I even rebuild the Nodes from scratch using the Azure Stack HCI 20H2 - Evaluation Guide - No luck

I have even added another member server and installed Windows Admin Center on it and then created cluster - No luck.

I am sure other have also faced the same problem but may be too busy to post it here. 

Anything insight or guidance would be greatly appreciated

**Comment by ellenkirby** [comment]
Thanks for letting us know about your issue. We will test the lab over the next few days and follow up.

**Comment by WVDAdminTF** [comment]
Hi Ellen,


Thank you so much for responding, please let me kow the status as we have an upcoming Microsoft Training for the same in January 2022. Hope we are able to fix it by then.



Regards,



Iqbal Johar

Trainer & Solutions Architect- Cloud & Mobility

Office 365 | Microsoft Azure | Microsoft 365

MCT | MCA | MCSE | MCSA | MCTS |MCITP

+91 7045540961 | Technofocus<http://www.technofocus.in/>

________________________________

**Comment by ellenkirby** [comment]
Iqbal,

We have deployed the lab and believe the issue no longer exists. Please retry and let us know if you are still experiencing issues.
