### ISSUE TITLE
cannot create volume due to S2D configuration issue

### ISSUE THREAD

**Issue by Ferasshehadeh** [Azure/AzureStackHCI-EvalGuide#70]
after running the script we got 
000010b8.00000540::2021/12/08-19:34:02.433 INFO  [Provider {29d1f3ee-dbcf-44e9-b0cc-085bfa362499}] StoragePoolEventInterpreter::ProcessPoolTransactionEvents - Wrote HealthDataStore at key:{xxxxxxxxx}:SP:{xxxxxx} name:StoragePoolFailureEventData with value 132834525225620000, EventStatus:3221226593. -- > STATUS_DISK_RESOURCES_EXHAUSTED The physical resources of this disk have been exhausted

**Comment by ercohen19** [comment]
Thanks for letting us know about your issue. We will test the lab over the next few days and follow up.

**Comment by ercohen19** [comment]
Hi, can you clarify which script you ran that caused this error? If possible, please attach an image of the entire PowerShell window with the command you executed and the resulting error. Thanks!

**Comment by Ferasshehadeh** [comment]
Hello Eleanor,

This was done by someone else and they opened a ticket with CSS MS.
They went through the steps which the article intended to be for multiple times, but they always experienced the S2D error that does not have enough space to create a volume.

Could not have time to repro, but if you could not most probably its a customer error.
However wanted to highlight in case was not tested.


Thanks
Feras.

**Comment by ercohen19** [comment]
Hi Feras,

Yes, sorry I was not able to repro the issue. I reran the lab this week and successfully created a volume. I would recommend that the customer redeploy their cluster and try again. Let me know if they continue running into errors.

Thanks,
Ellie
