### ISSUE TITLE
Unable to create volume due to $ParityTier , error.  How can this be resolved ? 

### ISSUE THREAD

**Issue by DivyaDatta** [Azure/AzureStackHCI-EvalGuide#71]
Following through the guide , cluster and two nodes are up . 
Before creating VM , volume should be prepared for VM 
Currently its failing with below error .. how do we resolve this issue ? 

Couldn't create the volume. Error: The variable '$ParityTier' cannot be retrieved because it has not been set.

**Comment by ercohen19** [comment]
Thanks for letting us know about your issue. We will test the lab over the next few days and follow up.
