### ISSUE TITLE
Cluster quit working

### ISSUE THREAD

**Issue by Phydeauxman** [Azure/AzureStackHCI-EvalGuide#72]
Used this Eval Guide to create a nested HCI instance in Azure Commercial...guide was fantastic and worked great. Problem I have as of this morning, when I start my Host VM, the cluster nodes will no longer start. I get the message in the image attached below:

![HCI_cluster_node_failure](https://user-images.githubusercontent.com/16844071/154529645-6665bd1d-6992-4b9a-9c74-a6a780eb0e60.jpg)

**Comment by ercohen19** [comment]
Hello thanks for letting us know about your issue. Yesterday, I encountered this error as well. But today the cluster is working again. Try restarting the Azure VM and then starting each nested server.

**Comment by Phydeauxman** [comment]
@ercohen19 tried starting my cluster again today and still having the same issue

**Comment by ercohen19** [comment]
Hi I have experienced the same issue. I recommend redeploying your cluster. My new cluster is up and running with no issues.

**Comment by Phydeauxman** [comment]
@ercohen19 when you say `re-deploy the cluster` do you mean destroy the host and start from scratch with the Eval Guide or just destroy the cluster on the existing host?

**Comment by ercohen19** [comment]
Destroy the host and start from scratch with the Eval Guide. I would recommend deleting the entire resource group as well or creating a new one.

**Comment by ercohen19** [comment]
Marking this issue as closed.
