### ISSUE TITLE
Question: Network ATC support

### ISSUE THREAD

**Issue by tksh164** [Azure/AzureStackHCI-EvalGuide#80]
Is this guide supporting the deploy Azure Stack HCI environment with Network ATC?

Tried deploying with Network ATC but failed deploy host network settings with the following error.

> Error: Exception calling "ReadExistingGoalStatesForAllNodes" with "2" argument(s): "Failed to open local cluster"

![image](https://user-images.githubusercontent.com/1618784/157073627-8b3f62b8-88d1-4413-bed7-a590ad3c21fe.png)

I'm guessing that CNO's IP address is lost during the host networking settings deployment because the CNO's IP address is not showing in Hyper-V manager after the host networking settings deployment. Also not finished the configuration for the ConvergedNic3 because the network adapter has lost IP address.

![image](https://user-images.githubusercontent.com/1618784/157074774-06c80a20-ae08-4f33-a5d3-4e336166e7f9.png)

![image](https://user-images.githubusercontent.com/1618784/157074815-1bb220b4-77d8-4999-9fe7-90ab763b4b54.png)

**Environnement Info:**
- Azure Stack HCI OS: 10.0.20348.288
- Windows Admin Center: Version 2110, Build 1.3.2111.01001
- Using Azure VM with nested virtualization.

**Comment by mgodfre3** [comment]
This is one of the first newly planned updates to this documentation. I will be working on this during the week. Thanks for the feedback.

**Comment by tksh164** [comment]
@mgodfre3 Thanks for comments. Got it.
