### ISSUE TITLE
Unable to pass test on Define Network pages

### ISSUE THREAD

**Issue by vovogit** [Azure/AzureStackHCI-EvalGuide#81]
I'm following the steps in the guide but the connectivity test doesn't pass on 'Define Network' pages. Do you know how to pass the test? 

I have already updated Cluster Creation Extension - version 2.38.0

Error details:
 - Message: 
    We couldn't configure adapter
 - Error: 
    We couldn’t configure and test network adapters. Please try again. Error: Command already contains prefix

<img width="942" alt="image" src="https://user-images.githubusercontent.com/53027809/160163206-6b78cddb-cc5b-4e50-aadd-a2976bff2254.png">

<img width="952" alt="image" src="https://user-images.githubusercontent.com/53027809/160163355-a8eb4278-c38e-492f-b9f2-4f2060fcbb14.png">

**Comment by ercohen19** [comment]
Hello! This is a known issue. Please downgrade 2 Windows Admin Center extensions to versions earlier than Cluster Creation v1.577.0 and Cluster Manager v 2.15.0. Let me know if the issue persists thanks!

**Comment by vovogit** [comment]
Hi, ercohen19. thanks for you replying! I'll try your suggestion later!

**Comment by vovogit** [comment]
I updated Cluster Creation and Cluster Manager to the latest version as of 3/31/2022, then the connection test passed.

- Cluster Creation v2.39.0
- Cluster Manager v2.69.0

![image](https://user-images.githubusercontent.com/53027809/160965516-d1f54ed5-7ae1-4f3d-9d6e-2ace650e121c.png)

![image](https://user-images.githubusercontent.com/53027809/160965682-1e97419c-64ec-427b-9d0b-bbb0c407038a.png)
