### ISSUE TITLE
Issue deploying template DSC Config: A drive with the name 'AD' does not exist

### ISSUE THREAD

**Issue by chriselleman-msft** [Azure/AzureStackHCI-EvalGuide#84]
Trying to deploy the Arm template into Azure, it fails at the AzSHCIHost001/ConfigureAzSHCIHost step, the error which is returned is:
{
    "status": "Failed",
    "error": {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'ConfigureAzSHCIHost'. Error message: \"DSC Configuration 'AzSHCIHost' completed with error(s). Following are the first few: PowerShell DSC resource MSFT_ScriptResource  failed to execute Set-TargetResource functionality with error message: Cannot find drive. A drive with the name 'AD' does not exist.  The SendConfigurationApply function did not succeed. LCM failed to start desired state configuration manually.\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionDSCWindowsTroubleshoot "
    }
}

Region is East US, and Resource Group name is AzSHCILabRg, attempted using both MSDN and Internal accounts.

**Comment by mgodfre3** [comment]
Attempting to RePro.

**Comment by mgodfre3** [comment]
Fixed this issue with latest pull request. Confirmed through tests with user.
