### ISSUE TITLE
Script missing after phase 1

### ISSUE THREAD

**Issue by fe77** [Azure/AzureStackHCI-EvalGuide#86]
Team
I am at the step where the VM is created, and I am supposed to run some script :https://github.com/Azure/AzureStackHCI-EvalGuide/blob/main/deployment/steps/1_DeployAzureVM.md#troubleshooting
Unfortunatly I am blocked here. According to the documentation I am am supposed to have a directory but it is not there 

![hci](https://user-images.githubusercontent.com/42291329/171914567-41866aad-22cd-4d53-b3a4-836a9e1add99.jpg)
Could you advise me ?
Thanks a lot
fred

**Comment by fe77** [comment]
Hi,
I decided to go back and this time have been able to pass this stage.
What I have discovered is tha name change in the path, making the script to fail.
Thanks
fred

**Comment by mgodfre3** [comment]
Ok Thanks, was going to look at this today. Glad you made it past. LMK of any more issues.
