### ISSUE TITLE
DSC in a loop copying vhdx

### ISSUE THREAD

**Issue by Dragmarr** [Azure/AzureStackHCI-EvalGuide#87]
Trying to deploy the Template into Azure, it fails at the AzSHCIHost001/ConfigureAzSHCIHost.

The error which is returned is:
"statusMessage": "{\"status\":\"Failed\",\"error\":{\"code\":\"ResourceOperationFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\",\"details\":[{\"code\":\"VMExtensionProvisioningError\",\"message\":\"VM has reported a failure when processing extension 'ConfigureAsHciHost'. Error message: \\\"DSC Configuration 'ASHCIHost' completed with error(s). Following are the first few: Exception setting \\\"TargetPath\\\": \\\"Interface not registered\\r\\n\\r\\nFailed to find proxy registration for IID: {ADD8BA80-002B-11D0-8F0F-00C04FD7D062}.\\\" The PowerShell DSC resource '[cShortcut]BuildScript' with SourceInfo 'C:\\\\Packages\\\\Plugins\\\\Microsoft.Powershell.DSC\\\\2.83.2.0\\\\DSCWork\\\\ashcihost.0\\\\ashcihost.ps1::106::5::cShortcut' threw one or more non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details. The SendConfigurationApply function did not succeed. LCM failed to start desired state configuration manually.\\\"\\r\\n\\r\\nMore information on troubleshooting is available at https://aka.ms/VMExtensionDSCWindowsTroubleshoot \"}]}}",

Thanks.

**Comment by beckersfa** [comment]
I've got the same issue as Dragmarr. Anybody any idea?

**Comment by beckersfa** [comment]
I deployed the template again from scratch, works as expected now.

**Comment by Dragmarr** [comment]
Thanks beckersfa - can confirm that the template deployed as expected for me too this morning. I tried to re-deploy a few times last week but kept failing so happy it working today.
