### ISSUE TITLE
WAC Install VM Request

### ISSUE THREAD

**Issue by kristopherjturner** [Azure/AzureStackHCI-EvalGuide#89]
Not an issue but a request?  I have found that using the auto-update feature for WAC sometimes doesn't work.  So the next solution is to click the link to download WAC.  However, that doesn't work either cause WAC was deployed on the host which is now a Domain controller.  Would it be possible in future releases to have the solution deploy a third VM on the host along with node01 and node02 and have WAC deployed to that VM?

**Comment by Karl-WE** [comment]
mind there is now also a new method to access on-prem servers via Azure Portal through WAC without installing a Gateway VM or similar. All you need is an Azure Arc enabled server. Maybe this could prove a great alternative to a WAC Gateway VM installation in future.
