### ISSUE TITLE
Validation cluster failed

### ISSUE THREAD

**Issue by paracetamol32** [Azure/AzureStackHCI-EvalGuide#9]
Validation cluster failed when retrieving report:
![image](https://user-images.githubusercontent.com/14573835/88203701-82a94900-cc4a-11ea-9daf-0687c94af1a3.png)

![image](https://user-images.githubusercontent.com/14573835/88203773-9ce32700-cc4a-11ea-88b3-25c6670c4975.png)

**Comment by mattmcspirit** [comment]
Thanks - we'll look into this and update when we know more

**Comment by mattmcspirit** [comment]
On each node, can you run the following:

```
Restart-Service WinRm
```

Can you reboot the nodes, and also reboot the MGMT01 VM, then try again?

**Comment by mattmcspirit** [comment]
I've also added some workaround steps here: https://github.com/Azure/AzureStackHCI-EvalGuide/blob/main/nested/steps/4_AzSHCICluster.md#troubleshooting-cluster-validation-issues

**Comment by paracetamol32** [comment]
Restart-Service WinRm and reboot on all nodes and mgmt don't solve problem

**Comment by mattmcspirit** [comment]
Hey - did you deploy with EN-US as your region for AzSHCI nodes or select a different region?

**Comment by pminnebach** [comment]
I have the same error.

Both nodes and mgmt are deployed with Belgium as region.

After `Set-WinSystemLocale -SystemLocale en-us` , as per your previous request for both nodes and mgmt, it still is giving me the same error about the test report.

I did some troubleshooting with the locale and cultures, and I found out that it's the different culture was being the culprit in my case.
`Get-Culture` also reported nl-be back to me, and after setting it to en-us validation finally passed.

So now `Get-WinSystemLocale`, `Get-Culture` and `Get-UICulture` are set to en-us.

**Comment by mattmcspirit** [comment]
Thank you for troubleshooting - to confirm, running:

```powershell
Set-Culture -CultureInfo en-us
```

On the nodes, WAC management machine, or both, fixed it for you?

Thanks!

**Comment by pminnebach** [comment]
Yes, I can confirm it fixed it for me.

**Comment by mattmcspirit** [comment]
Thanks - but did you run this on just the nodes, or the WAC machine also?

**Comment by pminnebach** [comment]
On every machine, nodes and mgmt, just to make sure they are all the same.

**Comment by mattmcspirit** [comment]
Great - thanks, I'll try this and add to the guide notes when I have a workaround.

**Comment by paracetamol32** [comment]
I confirm it works
![image](https://user-images.githubusercontent.com/14573835/88490088-5454a200-cf99-11ea-82e9-d565d5368ab9.png)
