### ISSUE TITLE
Branch 21H2 refere to main scripts

### ISSUE THREAD

**Issue by hemetz** [Azure/AzureStackHCI-EvalGuide#92]
the scripts always refere to the main branch. This causes deployments issues and also brake the deployment for the 21H2 branch.
link from the deployment: 
 https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FAzureStackHCI-EvalGuide%2Fmain%2Fdeployment%2Fjson%2Fazshcihost.json

**Comment by hemetz** [comment]
should be resolved with pull request #93

**Comment by mgodfre3** [comment]
Approved pr
