### ISSUE TITLE
Error when trying to Enable AKS on AzSHCI (Azure based) Eval

### ISSUE THREAD

**Issue by scuijr** [Azure/AzureStackHCI-EvalGuide#95]
On the last step of Set Up AKS, my cluster keeps getting this error..  what's wrong?  Seems as if the cluster is trying a dead 404..

Message
Applying platform configurations failed. Error: GetCatalog error returned by API call: Post "https://msk8s.api.cdp.microsoft.com/api/v1.1/contents/default/namespaces/default/names/aks-hci-stable-catalogs-int/versions/latest?action=select": POST https://msk8s.api.cdp.microsoft.com/api/v1.1/contents/default/namespaces/default/names/aks-hci-stable-catalogs-int/versions/latest?action=select giving up after 6 attempt(s): Received unexpected response code: 404

**Comment by mgodfre3** [comment]
Did you use the EvalGuide or the HCI Sandbox method, the sandbox method is verified to work with AKS, as long as you disable the SDN deployment in the config  file, see Readme. The Sandbox can be found at aka.ms/azstackhcisandbox.  

You issue is more in line with deploying AKS on HCI as well, so not in the deployment of the Eval Guide.

**Comment by scuijr** [comment]
I used the Eval Guide to build it out and it was successful.  I can spin up VMs etc like the guide indicates.  However I tried to go thru the wizard for the AKS set up and thats where it fails.  I'm thinking the Eval cant do both.

**Comment by tksh164** [comment]
@scuijr Your error message looks the same as https://github.com/Azure/aks-hci/issues/194 Use latest AksHci module may resolve the issue.

**Comment by scuijr** [comment]
Hmm, I used the Eval Guide that has it deployed in Azure using the available template.  Not sure how I'd change to the latest module.

**Comment by mgodfre3** [comment]
the hci cluster can handle both, what cant handle aks together on the same cluster is SDN.  That is currently in Private preview. I would recommend installing AKS with PowerShell directly .  https://docs.microsoft.com/en-us/azure-stack/aks-hci/kubernetes-walkthrough-powershell

You need to update the powershell module for AKSHCI,  please refer to the guide above, but the command is:
Install-Module -Name AksHci -Repository PSGallery

**Comment by scuijr** [comment]
thanks!  I will try that..  yes I was sure to set the SDN argument to False.

**Comment by mgodfre3** [comment]
If you have a config file that you set ConfigureNC to $false, then you actually deployed the HCI Sandbox. If so, you need to run the InstallAKS script, as it has the networks preset for AKS, which in this case is vlan 200. The script is located in the Sandbox folder and is copied over to the AdminCenter VM, please run it there.

**Comment by mgodfre3** [comment]
Closing issue with no new updates
