### ISSUE TITLE
Deployment step 'AzSHCIHost001/ConfigureAzSHCIHost' Failing

### ISSUE THREAD

**Issue by thevlf** [Azure/AzureStackHCI-EvalGuide#96]
I did try the steps listed in the tshooting section:
cd "C:\Packages\Plugins\Microsoft.Powershell.DSC\*\DSCWork\azshcihost.0\AzSHCIHost"
Set-DscLocalConfigurationManager  -Path . -Force
Start-DscConfiguration -Path . -Wait -Force -Verbose

But still getting the following:
![image](https://user-images.githubusercontent.com/19673330/179896095-e802f521-4995-4a51-b477-210710ab9704.png)

**Comment by mgodfre3** [comment]
Duplicate issue with #91. Closing this issue and will track predecessor issue.
